name = "iwona-szymon-snaps"
main = "src/functions/api/[[path]].ts"
compatibility_date = "2023-07-18"

[site]
bucket = "dist"

[[d1_databases]]
binding = "MY_DATABASE"
database_name = "my-wedding-db"
database_id = "c3750e55-38c4-4ac1-ba60-7b66f81705ad"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-wedding-photos"
